//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BugFeed.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Urls {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Urls() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("BugFeed.Properties.Urls", typeof(Urls).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ~/Dashboard/Programas/AnalisarRelatorios.aspx.
        /// </summary>
        internal static string AnalisarRelatorio {
            get {
                return ResourceManager.GetString("AnalisarRelatorio", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ~/Dashboard/.
        /// </summary>
        internal static string Dashboard {
            get {
                return ResourceManager.GetString("Dashboard", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ~/Dashboard/Pesquisador/.
        /// </summary>
        internal static string DashboardPesquisador {
            get {
                return ResourceManager.GetString("DashboardPesquisador", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ~/Dashboard/Pesquisador/EnviarRelatorio.aspx.
        /// </summary>
        internal static string EnviarRelatorio {
            get {
                return ResourceManager.GetString("EnviarRelatorio", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ~/Dashboard/Programas/.
        /// </summary>
        internal static string GerenciamentoProgramas {
            get {
                return ResourceManager.GetString("GerenciamentoProgramas", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ~/Dashboard/Programas/ListaRelatorios.aspx.
        /// </summary>
        internal static string ListaRelatorios {
            get {
                return ResourceManager.GetString("ListaRelatorios", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ~/Dashboard/Programas/Novo.aspx.
        /// </summary>
        internal static string NovoPrograma {
            get {
                return ResourceManager.GetString("NovoPrograma", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ~/Dashboard/Programas/Pagamento.aspx.
        /// </summary>
        internal static string PagamentoRecompensa {
            get {
                return ResourceManager.GetString("PagamentoRecompensa", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ~/Dashboard/Pesquisador/Programa.aspx.
        /// </summary>
        internal static string ProgramaPesquisador {
            get {
                return ResourceManager.GetString("ProgramaPesquisador", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ~/Dashboard/Pesquisador/ProgramasAbertos.aspx.
        /// </summary>
        internal static string ProgramasAbertos {
            get {
                return ResourceManager.GetString("ProgramasAbertos", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ~/Dashboard/Programas/Relatorio.aspx.
        /// </summary>
        internal static string Relatorio {
            get {
                return ResourceManager.GetString("Relatorio", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ~/Account/SignIn.aspx.
        /// </summary>
        internal static string SignIn {
            get {
                return ResourceManager.GetString("SignIn", resourceCulture);
            }
        }
    }
}
